name: 'deacademy_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'


vars:
   wrk_schema: BRONZE
   file_format_json: DEACADEMY_MYDB.BRONZE.MY_CSV_FORMAT
   purge_status: FALSE
   stage_name: DEACADEMY_MYDB.BRONZE.deacademy_s3_test_stage/
   rawhist_db: DEACADEMY_MYDB

# Directory configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Configuring models
models:

  deacademy_dbt:
      silver:
          +schema: silver
          materialized: table
      gold:
          +schema: gold
          materialized: view

 

# Delete or comment out the 'project1' and 'project2' blocks entirely.
# Also remove the +database: RAW from seeds and snapshots for now.