name: 'deacademy_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

vars:
  target_db: GLUEDB_PRODUCTION
  target_schema: PUBLIC
  stage_name: GLUEDB_PRODUCTION.PUBLIC.GLUE_S3_STAGE

# Directory configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Configuring models
models:
  deacademy_dbt:
    staging:
      +materialized: view

    mart:
      +materialized: table

    demo:
      +materialized: table


# Delete or comment out the 'project1' and 'project2' blocks entirely.
# Also remove the +database: RAW from seeds and snapshots for now.