
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
<<<<<<< HEAD
name: 'my_new_project'
=======
<<<<<<< HEAD
name: 'my_new_project'
=======
name: 'deacademy_dbt'
>>>>>>> 185a219524f5737816f41f38fd859e238891ab6a
>>>>>>> e025dbe24f03d3f374d891327e18df0fee25e302
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

<<<<<<< HEAD

vars:

   target_db: GLUEDB
   target_schema: PUBLIC
   stage_name: GLUEDB.PUBLIC.GLUE_S3_STAGE



=======
>>>>>>> e025dbe24f03d3f374d891327e18df0fee25e302
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

<<<<<<< HEAD
# models:
#   my_new_project:
#     # Applies to all files under models/example/
#     example:
#       +materialized: table
=======
models:
<<<<<<< HEAD
  my_new_project:
    # Applies to all files under models/example/
    example:
      +materialized: table
=======
  deacademy_dbt:
    +database: GLUEDB
    marts:
      +materialized: table
    # Applies to all files under models/example/
    demo:
      +materialized: table
    project1:
      +database: PROJECT1_DB
      bronze:
        +schema: BRONZE
      silver:
        +schema: silver
      marts:
        +materialized: table
        +schema: marts
    project2:
      +database: PROJECT2_DB
      raw:
        +schema: RAW
      mart:
        +materialized: table
        +schema: MART
    staging:
      +materialized: view
      +schema: staging
    


# ADD THIS FOR SEEDS
seeds:
  deacademy_dbt:
    +database: RAW
    +schema: jaffle_shop
# ADD THIS FOR SNAPSHOTS
snapshots:
  deacademy_dbt:
    +database: DBT_DB_PROD


>>>>>>> 185a219524f5737816f41f38fd859e238891ab6a
>>>>>>> e025dbe24f03d3f374d891327e18df0fee25e302
