name: 'deacademy_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

vars:
  target_db: GLUEDB
  target_schema: PUBLIC
  stage_name: GLUEDB.PUBLIC.GLUE_S3_STAGE

# Directory configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  deacademy_dbt:
    +database: GLUEDB
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
    demo:
      +materialized: table
    
    # Project specific configurations
    project1:
      +database: PROJECT1_DB
      bronze:
        +schema: BRONZE
      silver:
        +schema: silver
      marts:
        +materialized: table
        +schema: marts
    project2:
      +database: PROJECT2_DB
      raw:
        +schema: RAW
      mart:
        +materialized: table
        +schema: MART

seeds:
  deacademy_dbt:
    +database: RAW
    +schema: jaffle_shop

snapshots:
  deacademy_dbt:
    +database: DBT_DB_PROD