version: 2

sources:
  # --- YOUR NEW WALMART PROJECT ---
  - name: walmart_raw
    database: WALMART_PROJECT
    schema: PUBLIC
    tables:
      - name: stg_department
      - name: stg_stores
      - name: stg_fact

  # --- OLD SOURCE NEEDED BY TRANSFORM_PRODUCT_LOAD ---
  - name: source
    database: DEACADEMY_MYDB 
    schema: BRONZE
    tables:
      - name: WORK_PRODUCT_COPY