version: 2

sources:
  - name: patient
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: PATIENT_SRC

  - name: employee          # This matches the first part of {{ source('employee', ...) }}
    database: DBT_DB        # Update if this lives in a different DB
    schema: PUBLIC          # Update if this lives in a different schema
    tables:
      - name: EMPLOYEE_RAW  # This matches the second part of the source call
        config:
          loaded_at_field: updated_at # Moves the property to config to stop the warning

  - name: source
    database: DEACADEMY_MYDB  # Raw data lives here
    schema: BRONZE
    tables:
      - name: WORK_PRODUCT_COPY

  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment
        config:
          loaded_at_field: _BATCHED_AT